type AdminTableConfig = {
  key: string;
  label: string;
  description: string;
  group: "Treści" | "Sport" | "Klub" | "System";
  editorHref?: string;
  columns: readonly string[];
};

export const adminTableConfigs = [
  {
    key: "articles",
    label: "Artykuły",
    description: "Aktualności klubowe, status publikacji i metadane.",
    group: "Treści",
    editorHref: "/admin/articles",
    columns: [
      "title",
      "status",
      "publishedAt",
      "imageStorageId",
      "galleryIds",
      "metaTitle",
      "metaDescription",
      "ogImageStorageId",
    ],
  },
  {
    key: "fbPosts",
    label: "Posty Facebook",
    description: "Treści zsynchronizowane wraz z zasięgami i kategoryzacją.",
    group: "Treści",
    editorHref: "/admin/fb-posts",
    columns: [
      "content",
      "imageStorageId",
      "imageIds",
      "videoUrl",
      "linkUrl",
      "commentsCount",
      "sharesCount",
      "syncedAt",
    ],
  },
  {
    key: "galleries",
    label: "Galerie",
    description: "Albumy, zdjęcia i powiązania z drużynami.",
    group: "Treści",
    editorHref: "/admin/galerie",
    columns: ["title", "date", "teamId", "imageIds", "slug"],
  },
  {
    key: "documents",
    label: "Dokumenty",
    description: "Pliki publikowane w sekcji dokumentów klubu.",
    group: "Treści",
    editorHref: "/admin/dokumenty",
    columns: ["title", "category", "sortOrder", "fileStorageId"],
  },
  {
    key: "pages",
    label: "Strony",
    description: "Treści statycznych stron i ich metadane SEO.",
    group: "Treści",
    columns: ["title", "slug", "metaTitle", "metaDescription"],
  },
  {
    key: "matches",
    label: "Mecze",
    description: "Terminarz, wyniki, źródła i materiały wideo.",
    group: "Sport",
    editorHref: "/admin/mecze",
    columns: [
      "homeTeam",
      "awayTeam",
      "date",
      "dateConfirmed",
      "result",
      "status",
      "matchType",
      "teamId",
    ],
  },
  {
    key: "matchEvents",
    label: "Zdarzenia meczowe",
    description: "Bramki, asysty i kartki przypisane do spotkań.",
    group: "Sport",
    columns: ["playerName", "type", "minute", "teamSide", "matchId"],
  },
  {
    key: "teams",
    label: "Drużyny",
    description: "Zespoły, roczniki, trenerzy i status widoczności.",
    group: "Sport",
    editorHref: "/admin/druzyny",
    columns: ["name", "yearGroup", "league", "isActive", "schedule"],
  },
  {
    key: "players",
    label: "Zawodnicy",
    description: "Kadry zawodnicze przypisane do drużyn.",
    group: "Sport",
    editorHref: "/admin/kadry",
    columns: ["name", "number", "teamId", "sortOrder", "photoStorageId"],
  },
  {
    key: "standings",
    label: "Tabele ligowe",
    description: "Klasyfikacje rozgrywek pobierane ze źródeł.",
    group: "Sport",
    columns: ["competitionName", "season", "teamId", "syncedAt", "rows"],
  },
  {
    key: "liveStreams",
    label: "Transmisje",
    description: "Zaplanowane, aktywne i zakończone transmisje.",
    group: "Sport",
    editorHref: "/admin/live",
    columns: ["title", "status", "startsAt", "endedAt", "youtubeUrl"],
  },
  {
    key: "people",
    label: "Ludzie",
    description: "Trenerzy, zarząd, legendy i zasłużeni.",
    group: "Klub",
    editorHref: "/admin/ludzie",
    columns: ["name", "role", "position", "teamId", "qualifications"],
  },
  {
    key: "sponsors",
    label: "Sponsorzy",
    description: "Sponsorzy i partnerzy wraz z kolejnością ekspozycji.",
    group: "Klub",
    editorHref: "/admin/sponsorzy",
    columns: ["name", "type", "label", "url", "sortOrder"],
  },
  {
    key: "regulationAcceptances",
    label: "Akceptacje regulaminu",
    description: "Zgody opiekunów, wersje dokumentów i dane formularza.",
    group: "Klub",
    editorHref: "/admin/regulamin",
    columns: [
      "childName",
      "childPesel",
      "parentName",
      "parentPesel",
      "acceptedRegulation",
      "acceptedChildProtection",
      "acceptedDataProcessing",
      "acceptedAt",
    ],
  },
  {
    key: "syncSources",
    label: "Źródła synchronizacji",
    description: "Połączenia z terminarzami oraz stan ostatniej synchronizacji.",
    group: "System",
    editorHref: "/admin/druzyny",
    columns: ["kind", "teamNameOnSource", "enabled", "lastSyncedAt", "lastError"],
  },
  {
    key: "settings",
    label: "Ustawienia strony",
    description: "Dane kontaktowe i pozostałe ustawienia tekstowe.",
    group: "System",
    editorHref: "/admin/ustawienia",
    columns: ["key", "value"],
  },
  {
    key: "appSettings",
    label: "Ustawienia aplikacji",
    description: "Flagi i wartości sterujące automatyzacjami aplikacji.",
    group: "System",
    editorHref: "/admin/mecze",
    columns: ["key", "boolValue", "stringValue", "numberValue"],
  },
  {
    key: "storage",
    label: "Pliki w storage",
    description: "Obiekty w Convex Storage wraz z rozmiarem, typem i bezpiecznym adresem podglądu.",
    group: "System",
    columns: ["contentType", "size", "_creationTime", "sha256", "url"],
  },
] as const satisfies readonly AdminTableConfig[];

export type AdminTableName = (typeof adminTableConfigs)[number]["key"];

export const adminTableConfigByName = Object.fromEntries(
  adminTableConfigs.map((config) => [config.key, config]),
) as unknown as Record<
  AdminTableName,
  AdminTableConfig & { key: AdminTableName }
>;

export const adminFieldLabels: Record<string, string> = {
  acceptedAt: "Data akceptacji",
  acceptedChildProtection: "Ochrona małoletnich",
  acceptedDataProcessing: "Przetwarzanie danych",
  acceptedRegulation: "Regulamin",
  _creationTime: "Utworzono",
  awayTeam: "Gość",
  boolValue: "Wartość logiczna",
  category: "Kategoria",
  childName: "Dziecko",
  childPesel: "PESEL dziecka",
  childYearGroup: "Rocznik",
  coachId: "ID trenera",
  commentsCount: "Komentarze",
  competitionName: "Rozgrywki",
  contentType: "Typ pliku",
  content: "Treść",
  date: "Data",
  dateConfirmed: "Termin potwierdzony",
  enabled: "Aktywne",
  endedAt: "Zakończono",
  fileStorageId: "ID pliku",
  homeTeam: "Gospodarz",
  imageStorageId: "Zdjęcie główne",
  imageIds: "Zdjęcia",
  galleryIds: "Galeria artykułu",
  isActive: "Widoczna",
  isHidden: "Ukryty",
  key: "Klucz",
  kind: "Źródło",
  label: "Etykieta",
  lastError: "Ostatni błąd",
  lastSyncedAt: "Ostatnia synchronizacja",
  league: "Liga",
  linkUrl: "Link docelowy",
  matchId: "ID meczu",
  matchType: "Rodzaj meczu",
  metaDescription: "Opis SEO",
  metaTitle: "Tytuł SEO",
  minute: "Minuta",
  name: "Nazwa",
  number: "Numer",
  numberValue: "Wartość liczbowa",
  ogImageStorageId: "Obraz Open Graph",
  parentEmail: "E-mail opiekuna",
  parentName: "Opiekun",
  parentPesel: "PESEL opiekuna",
  photoStorageId: "ID zdjęcia",
  playerName: "Zawodnik",
  position: "Stanowisko",
  postType: "Typ posta",
  publishedAt: "Publikacja",
  reactionsCount: "Reakcje",
  qualifications: "Kwalifikacje",
  result: "Wynik",
  role: "Rola",
  rows: "Wiersze tabeli",
  schedule: "Harmonogram",
  season: "Sezon",
  sha256: "Suma SHA-256",
  sharesCount: "Udostępnienia",
  size: "Rozmiar",
  slug: "Slug",
  sortOrder: "Kolejność",
  startsAt: "Start",
  status: "Status",
  source: "Źródło",
  stringValue: "Wartość tekstowa",
  syncedAt: "Synchronizacja",
  teamId: "ID drużyny",
  teamNameOnSource: "Nazwa w źródle",
  teamSide: "Strona",
  title: "Tytuł",
  type: "Typ",
  url: "Adres URL",
  value: "Wartość",
  videoUrl: "Wideo",
  yearGroup: "Rocznik",
  youtubeUrl: "YouTube",
};

export function isAdminTableName(value: string | undefined): value is AdminTableName {
  return adminTableConfigs.some((config) => config.key === value);
}
